### ISSUE TITLE
[errorpages]

### ISSUE THREAD

**Issue by microniko** [getnikola/plugins#176] opened 2016-10-09 21:03 UTC
I install errorpages plugins but when I compiled the website, I have this error :

> $ nikola build 
> Scanning posts......done!
> Traceback (most recent call last):
>   File "/home/nicolas/envvirt/nikola/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run 
>     return command.parse_execute(args)
>   File "/home/nicolas/envvirt/nikola/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
>     return self.execute(params, args)
>   File "/home/nicolas/envvirt/nikola/lib/python3.5/site-packages/doit/cmd_base.py", line 380, in execute
>     self, params, args)
>   File "/home/nicolas/envvirt/nikola/lib/python3.5/site-packages/nikola/**main**.py", line 279, in load_tasks
>     self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
>   File "/home/nicolas/envvirt/nikola/lib/python3.5/site-packages/doit/loader.py", line 314, in generate_tasks
>     for task_dict, x_doc in flat_generator(gen_result, gen_doc):
>   File "/home/nicolas/envvirt/nikola/lib/python3.5/site-packages/doit/loader.py", line 28, in flat_generator
>     for item in gen:
>   File "/home/nicolas/envvirt/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1795, in gen_tasks
>     for task in flatten(pluginInfo.plugin_object.gen_tasks()):
>   File "/home/nicolas/envvirt/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1790, in flatten
>     for ft in flatten(t):
>   File "/home/nicolas/envvirt/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1789, in flatten
>     for t in task:
>   File "/home/nicolas/repo_site/plugins/errorpages/errorpages.py", line 117, in prepare_error_page
>     task = self.site.generic_renderer(lang, destination, template, self.site.config["FILTERS"], context=context, url_type=url_type)
> AttributeError: 'Nikola' object has no attribute 'generic_renderer'

What happens ?!

**Comment by felixfontein** [comment] 2016-10-10 04:44
The plugin depends on a feature in Nikola which was just merged into master yesterday (that implemented `generic_renderer`). You need to install the master branch from GitHub, or it doesn't work at the moment. (Also see the last paragraph in https://github.com/getnikola/plugins/blob/master/v7/errorpages/README.md.)

**Comment by microniko** [comment] 2016-10-10 05:47
Ok, thanks !
I'll wait the next release…
(404 error ;)

**Comment by felixfontein** [comment] 2016-10-10 06:13
Waiting is definitely less hassle (if you don't want to hack on Nikola anyway)... I don't know what the current release plans are, but usually it's not too long.

**Comment by Kwpolska** [comment] 2016-10-10 08:43
I'll attempt a release later this week.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by felixfontein** [comment] 2016-10-13 19:04
Nikola 7.8.1 is released now, so `errorpages` should now work out of the box. :)

**Comment by microniko** [comment] 2016-10-23 12:16
Woaw :-(
I updated Nikola to 7.8.1 but `errorpages` does not still work …

> $ nikola build
Scanning posts......done!
.  errorpages:output/404.html
########################################
TaskError - taskid:errorpages:output/404.html
PythonAction Error
Traceback (most recent call last):
  File "/home/toto/envvirt/nikola/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/toto/envvirt/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1318, in render_template
    template_name, None, local_context)
  File "/home/toto/envvirt/nikola/lib/python3.5/site-packages/nikola/plugins/template/mako.py", line 117, in render_template
    data = template.render_unicode(**context)
  File "/home/toto/envvirt/nikola/lib/python3.5/site-packages/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/home/toto/envvirt/nikola/lib/python3.5/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/toto/envvirt/nikola/lib/python3.5/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/toto/envvirt/nikola/lib/python3.5/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/toto/site/www/cache/.mako.tmp/base.tmpl.py", line 64, in render_body
    __M_writer(str(base.html_headstart()))
  File "/home/toto/site/www/cache/.mako.tmp/base_helper.tmpl.py", line 241, in render_html_headstart
    __M_writer(str(url_replacer(permalink, '/assets/js/html5.js', lang)))
  File "/home/toto/envvirt/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1370, in url_replacer
    src_elems = parsed_src.path.split('/')[1:]
TypeError: a bytes-like object is required, not 'str'

**Comment by felixfontein** [comment] 2016-10-23 12:46
Looks like some problem with the default theme. I don't use the default theme so I never experienced that.

**Comment by felixfontein** [comment] 2016-10-23 12:55
Looks like the default base plugin does some weird stuff with `url_replacer` and tries to insert relative links, which will obviously not work with error pages. What a mess. Also, it expects that every page has `permalink` set to the URL for the current page, which this plugin doesn't do.

**Comment by Kwpolska** [comment] 2016-10-23 13:00
You could work around the first issue by passing url_type to templates, and the second one by checking for permalink not being None, I guess. (Both are global changes to Nikola core. Speaking of which, getnikola/nikola#2544 could use a review)

**Comment by felixfontein** [comment] 2016-10-23 15:58
@microniko: the issue is now fixed if you use Nikola's master branch and the updated plugin.

**Comment by microniko** [comment] 2016-10-23 16:28
Thanks @felixfontein :)

**Comment by Kwpolska** [comment] 2017-05-24 18:13
Closing. If this still happens, we can always reopen.

**Closed by Kwpolska** 2017-05-24 18:13 UTC
